spring:
    datasource:
        password: 
        username: sa
        url: jdbc:h2:mem:qa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
banco:
  notas: "100.00, 50.00, 20.00, 10.00, 5.00, 1.00"
  moedas: "0.50, 0.25, 0.10, 0.05"          

